const PUBLIC_CODE_ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ";
const PUBLIC_CODE_LENGTH = 6;

// MVP uses a deterministic public code derived from user_id.
// This file is the only generator. Do not duplicate the algorithm elsewhere.
// If we later migrate to DB-managed public_code, we need a backfill step that
// preserves existing values generated by this function before switching reads.
export function publicUserCodeFromId(userId: string): string {
  let hash = 2166136261;
  const normalized = userId.replace(/-/g, "").toUpperCase();

  for (let index = 0; index < normalized.length; index += 1) {
    hash ^= normalized.charCodeAt(index);
    hash = Math.imul(hash, 16777619) >>> 0;
  }

  let value = hash;
  let code = "";
  for (let index = 0; index < PUBLIC_CODE_LENGTH; index += 1) {
    code = PUBLIC_CODE_ALPHABET[value % PUBLIC_CODE_ALPHABET.length] + code;
    value = Math.floor(value / PUBLIC_CODE_ALPHABET.length);
  }

  return code.padStart(PUBLIC_CODE_LENGTH, PUBLIC_CODE_ALPHABET[0]);
}
